default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:1081198957448:android:98033a89467e891075603d",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    groups: "testers",
    release_notes: "This is a Bug Tracking App release"
  )
  end
end
